### ISSUE TITLE
Manage web assets in a package.json

### ISSUE THREAD

**Issue by maconfr** [leoluk/configmaster#28]
Using a dependency manager such as npm or yarn makes it easier to manage dependencies.
It is easier to track used versions, whether updates are available and the libraries do not need to be included in the repository.

**Comment by leoluk** [comment]
+1 for yarn, but it imposes additional operational overhead. Right now we don't need it. After the UI rewrite, probably.

**Comment by maconfr** [comment]
The UI rewrite also seems to be a good opportunity to me.
+1 for yarn

**Comment by leoluk** [comment]
UI rewrite will take care of this.

npm has caught up with yarn nowadays, too
